### ISSUE TITLE
Замечания по паттерну "Команда"

### ISSUE THREAD

**Issue by alexey-malov** [Carapacik/ood_2020#1]
- [x] Редактирование изображения (ресайз) и параграфа (смена текста) должны выполняться через их интерфейсы, а не через document. Соответственно, Image и Paragraph должны при выполнении этих операций обеспечивать сохранение команд в историю правок. Сейчас же IImage и IParagraph позволяет выполнить эти изменения в обход системы команд

**Comment by alexey-malov** [comment]
```c#
    public class Paragraph : IParagraph
    {
        ...
        public void Delete()
        {
            throw new NotImplementedException();
        }
    }
```

- [x] Метод Delete нарушает Принцип подстановки Барбары Лисков. Класс декларирует, что реализует интерфейс IDocumentItem, а сам не поддерживает единственный метод этого интерфейса

**Comment by alexey-malov** [comment]
- [x] Интерфейс IDocument позволяет изменить заголовок документа в обход истории изменений

**Comment by alexey-malov** [comment]
- [x] При просмотре сохранённого документа в браузере Firefox не отображаются изображения. Во-первых, изображения должны иметь относительный путь, а во-вторых, должны использовать прямые слэши, чтобы корректно отображаться в браузере. В третьих, HTML-тэг `<img>` должен быть закрытым. Это невалидный html:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>No title</title>
  </head>
  <body>
	<img src="e:\temp\123\images\92cfe951-7bc2-4e47-9677-de473b9ea155.png" width="300" height="200"
  </body>
</html>
```

- [x] Покрыть сериализацию документа тестами

**Comment by alexey-malov** [comment]
- [x] Содержимое title-тэга должно html-encode-иться при сохранении документа

**Comment by alexey-malov** [comment]
```c#
        public DocumentSaver(List<IDocumentItem> documentItems)
        {
            _documentItems = documentItems;
        }

        public void Save(string path, string title)
        {
            ...
        }
```

- [x] С чем связано, что одна часть документа (его элементы) передаётся в конструктор, а другая (заголовок) - в метода Save? Хотя и тот, и другой берутся в одном и том же месте

**Comment by Carapacik** [comment]
Принято
