### ISSUE TITLE
Замечания по паттерну "Адаптер"

### ISSUE THREAD

**Issue by alexey-malov** [Carapacik/ood_2020#2]
- [x] На UML-диаграмме не показаны связи между адаптерами и адаптируемым классом ModernGraphicsRenderer

- [x] Также на диаграмме нужно показать границы модулей (GraphicsLib, ShapeDrawingLib, ModernGraphicsLib, Application) и разместить классы внутри соответствующих модулей

**Comment by alexey-malov** [comment]
- [x] Приложение упадёт, если в адапторе вызвать LineTo без предварительного вызова MoveTo

**Comment by alexey-malov** [comment]
```
2>E:\teaching\ood\2020\laptev\ood_2020\lab6\AdapterTests\ClassTests.cs(52,23,52,27): warning CS0219: The variable 'endY' is assigned but its value is never used
```
- [x] Программа должна компилироваться без предупреждений компилятора во всех конфигурациях и платформах.

**Comment by Carapacik** [comment]
> * [x]  Приложение упадёт, если в адаптере вызвать LineTo без предварительного вызова MoveTo

Есть тесты, где выдаёт ошибку, когда LineTo без BeginDraw, и есть тесты, где LineTo рисует с BeginDraw

**Comment by Carapacik** [comment]
Принято
